# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExampleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleProject
  #  pod 'Stylish-2', :git => 'https://github.com/pgawlowski/Stylish-2.git’

pod 'Stylish-2', :path => '/Users/pgawlowski/Documents/Projects/Stylish-2’

  target 'ExampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
          end
      end
  end
  
end
